### ISSUE TITLE
Breaking News -- Please read!

### ISSUE THREAD

**Issue by rmedinahu** [rmedinahu/cs451-lessons-dev-py#11]
Go here for information regarding final exam... -rm

https://nmhu.desire2learn.com/d2l/home/24560

**Comment by engenzi** [comment]
Hi Dr. M,It's Eric from your software engineering class. I wanted to talk to you about my grade because I gotta a C in final but I had an A in midterm so I thought that will make my final grade a B at least. I want to come discus it with you if you're in the office. Thank you very much for your time! Sent from Yahoo Mail for iPhone
